import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@careconnect.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'dark Mode' }).click();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'light Mode' }).click();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'Patients' }).click();
  await page.getByRole('button', { name: 'Add Patient' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('TEST');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('TEST');
  await page.getByRole('textbox', { name: 'Date of Birth' }).fill('2026-03-18');
  await page.getByLabel('Gender').selectOption('Prefer not to say');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('1234');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('some@email.com');
  await page.getByRole('button', { name: 'Register Patient' }).click();
  await page.getByRole('button', { name: 'TT TEST TEST Room Stable' }).click();
  await page.getByRole('button', { name: 'Tasks' }).click();
  await page.getByRole('button', { name: 'New Task' }).click();
  await page.getByRole('textbox', { name: 'e.g. Check vital signs' }).click();
  await page.getByRole('textbox', { name: 'e.g. Check vital signs' }).fill('TEST TASK');
  await page.getByRole('textbox', { name: 'e.g. John Davis' }).click();
  await page.getByRole('textbox', { name: 'e.g. John Davis' }).fill('TESTER');
  await page.locator('select[name="priority"]').selectOption('medium');
  await page.locator('select[name="category"]').selectOption('Treatment');
  await page.getByRole('button', { name: 'Create Task' }).click();
  await page.getByRole('textbox', { name: 'Search tasks...' }).click();
  await page.getByRole('textbox', { name: 'Search tasks...' }).fill('te');
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('button', { name: 'Start Task' }).click();
  await page.getByRole('button', { name: 'In Progress' }).click();
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
});